source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
xcodeproj 'hopeful2'

target :hopeful2 do

pod 'HSDatePickerViewController', '~> 1.0'
pod "TextFieldEffects"
pod "BSImagePicker", "~> 1.4.0"

end